// Generated by CoffeeScript 1.4.0

$(document).ready(function() {
  var background, connectButton, disconnectButton, hostField, portField;
  background = chrome.extension.getBackgroundPage();
  hostField = $('form#socketform #host');
  portField = $('form#socketform #port');
  connectButton = $('form#socketform #connect');
  disconnectButton = $('form#socketform #disconnect');
  $('#connect').on("click", function(e) {
    e.preventDefault();
    if ($(e.target).hasClass("disabled")) {
      return;
    }
    background.connect(hostField.val(), portField.val());
    return window.close();
  });
  $('#disconnect').on("click", function(e) {
    e.preventDefault();
    if ($(e.target).hasClass("disabled")) {
      return;
    }
    background.disconnect();
    return window.close();
  });
  return chrome.extension.sendMessage({
    command: "getInformation"
  }, function(response) {
    hostField.val(response.host);
    portField.val(response.port);
    connectButton.addClass('disabled');
    return disconnectButton.removeClass('disabled');
  });
});
